### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Arch9SK7** [olliz0r/Ledybot#16]

**Comment by olliz0r** [comment]
Hey,
the Box1Slot1 USUM should be 0x33015AB0, I can look for the wondercard one in a second.

Can you clarify what you mean with "pokebyte" offset?

**Comment by Arch9SK7** [comment]
might have been a mistake on my part there lol when i was trying to compare your source to pkhex and such to figure out exactly the sun and moon box offset i was thinking the pokebyte offset would be the placement of each pokemon into the box layout. Also thank you kindly for the answer.

**Comment by olliz0r** [comment]
Wondercard offset is probably 0x33075BF4,
let me know if it works.

**Comment by Arch9SK7** [comment]
Will add it in and test now :) i'll get back to you when i find out!

**Comment by Arch9SK7** [comment]
Hmm nothing... on either.. I am trying to add it for the injection process.

This syntax is correct am i not wrong?> 

public delegate void LogDelegate(string l);
        public LogDelegate delLastLog;
        public string lastlog = "";
        public int pid = 0;
        public PKHeX dumpedPKHeX = new PKHeX();

        public uint boxOff = 0x330D9838 + 0x33015AB0;           <<<<<<?
        public uint wcOff = 0x331397E4 + 0x33075BF4;              <<<<<<?
        public uint partyOff = 0x34195E10;

**Comment by olliz0r** [comment]
Well no, for SM you'd have to use 0x330D9838 for the box offset, for USUM you'd have to use 0x33015AB0 instead. So you need a function to figure out what game is being run and change the offsets accordingly. Should probably be the same function that determines the PID of the game right now

**Comment by Arch9SK7** [comment]
Damn you are right. why didn't i think of that... Thank you for that.

**Comment by Arch9SK7** [comment]
Hmm so i went back and even just changed out the offsets and changed a couple things and nothing. i don't believe the offsets were correct at all. or is there something else that needs to be changed to verify ultra games? Perhaps something within either of these?

        public void getGame(object sender, EventArgs e)
        {
            InfoReadyEventArgs args = (InfoReadyEventArgs)e;

            string log = args.info;
            if (log.Contains("niji_loc"))
            {
                string splitlog = log.Substring(log.IndexOf(", pname: niji_loc") - 8, log.Length - log.IndexOf(", pname: niji_loc"));
                pid = Convert.ToInt32("0x" + splitlog.Substring(0, 8), 16);
                Program.helper.pid = pid;
                Program.scriptHelper.write(0x3E14C0, BitConverter.GetBytes(0xE3A01000), pid);
                MessageBox.Show("Connection Successful!");
            }
        }

or here 

byte[] pkmEncrypted = System.IO.File.ReadAllBytes(tb_FileInjection.Text);
            byte[] cloneshort = PKHeX.encryptArray(pkmEncrypted.Take(232).ToArray());
            uint boxIndex = Decimal.ToUInt32((nud_BoxInjection.Value - 1) * 30 + nud_SlotInjection.Value - 1);
            uint count = Decimal.ToUInt32(nud_CountInjection.Value);
            if (boxIndex + count > 32 * 30)
            {
                uint newCount = 32 * 30 - boxIndex;
                count = newCount;
            }

            byte[] dataToWrite = new byte[count * 232];
            for (int i = 0; i < count; i++)
                cloneshort.CopyTo(dataToWrite, i * 232);
            uint offset = boxOff + boxIndex * 232;
            Program.scriptHelper.write(offset, dataToWrite, pid);
            MessageBox.Show("Injection Successful!");
        }

**Comment by Arch9SK7** [comment]
I even updated the game versions it should find within PKHeX.cs

    public class PKHeX
    {
        public bool Gen7 => Version >= 30 && Version <= 33;
        public bool Gen6 => Version >= 24 && Version <= 29;
        public bool Gen5 => Version >= 20 && Version <= 23;
        public bool Gen4 => Version >= 7 && Version <= 12 && Version != 9;
        public bool Gen3 => Version >= 1 && Version <= 5 || Version == 15;
        public bool GenU => !(Gen7 || Gen6 || Gen5 || Gen4 || Gen3);
        public int GenNumber
        {
            get
            {
                if (Gen7) return 7;
                if (Gen6) return 6;
                if (Gen5) return 5;
                if (Gen4) return 4;
                if (Gen3) return 3;
                return -1;
            }
        }

**Comment by Glitching-Queen** [comment]
@olliz0r Do you know the new Eggoffset? for does day care have egg available.
