### ISSUE TITLE
Another problem with Spanish Game

### ISSUE THREAD

**Issue by AlejaKaiser** [olliz0r/Ledybot#2]
When the bot search for a Pokémon, if the game it's in Spanish, instead trade with people, the bot start looping over and over without make trades. I think it's a error with the text because in Spanish the text it's a bit diferent (For example, Nivel instead level, "Del 91 al 100" instead "91 or higher", Pokémon deseado instead Pokémon wanted...)

Hope you could fix this issues in the future :)

**Comment by olliz0r** [comment]
Hey,

it seems different languages use different offsets for names and stuff in the memory. I uploaded a version with a little checkbox for the spanish offsets (default is english), you can try that one!

Tell me if it breaks, I only tested it very briefly!

(I fear more languages are gonna need to be added in the future)
