### ISSUE TITLE
How to make it so that recipients are required to nickname their pokemon, else, the bot won't trade them?

### ISSUE THREAD

**Issue by Naturally-Delicious** [olliz0r/Ledybot#20]

**Comment by imaboy321** [comment]
You can do this by filling out the GD Input while leaving the first browse option blank. Because you aren't selecting a default file, there is no method of autofilling the contents.

**Comment by Naturally-Delicious** [comment]
Thank you

**Comment by Naturally-Delicious** [comment]
@imaboy321 Wait what If I'm giving out multiple pokemon? If I rename them all to let say, "Dave", windows will auto put a (1) to the end of the pkhex file. (to distinguish the files) will ledybot take the parenthesis literal and check for it when searching a pokemon? I can't really test for myself since I only have one 3ds. also if ledybot does take it literally, is it possible to implement to toggle "ignore parenthesis" or not? Thanks!!

**Comment by imaboy321** [comment]
Are these files all the same pokemon species? If so it is impossible because then it wouldn't know which "Dave" to send. If they are opposite species, they would go in different directories and entries in the Giveaway Details.

**Comment by Naturally-Delicious** [comment]
(Not all same species)

That's what I thought... but it was a bit tedious so I thought there was an easier way... guess not, thanks for your time!!

**Comment by BornForGaming** [comment]
To me it looks like it seems to work if you create one folder for every Pokemon and place the nicknamed pk7 file (PKHEX FILE) inside. Go on giveaway details and select "add", from there on leave the "specific" one free and choose the folder from the Pokemon in the "optional" one. Works perfectly fine!

**Comment by Naturally-Delicious** [comment]
Yeah that's what I've been doing but it's so tedious when you got a lot of
Pokemon to distribute 😑
