### ISSUE TITLE
(I'm sorry for the new thread) Reddit tab broken?

### ISSUE THREAD

**Issue by Naturally-Delicious** [olliz0r/Ledybot#21]
So for the bot to check Reddit threads, trade to people with their flair etc., you have to put in the "code" of the giveaway thread. I just put in the 6 characters between comment and the title.

example

https://www.reddit.com/r/subreddit/comments/**123abc**/this_is_a_title/

anything else gives me errors. Anyways, I've noticed that the bot still trades to random people on the GTS. again, sorry for the numerous posts. if u want me to shut up just tell me 😃

**Comment by imaboy321** [comment]
Please make sure you have the latest version of the bot downloaded and have the Newtonsoft.Json.dll in the same directory as the Ledybot.exe. This is required for the Reddit functionality.

**Comment by Naturally-Delicious** [comment]
Yes that file is in the same directory as Ledybot. Both of the files are on my desktop though, dunno if that changes anything. Should I have them in a folder?

**Comment by imaboy321** [comment]
Having them on desktop should be fine. Just make sure it is fully updated. I was running with the latest version with no crashes with the reddit settings.

**Comment by Naturally-Delicious** [comment]
I don't get any crashes when I have reddit on or off, regardless of it's state, the bot still trades random people not from my giveaway.

**Comment by imaboy321** [comment]
Make sure you are checking the "Use FC Flairs" options before you click start. There definitely isn't an issue internally because it is working for many on r/PokemonPlaza.

**Comment by k20stitch** [comment]
Also make sure ledy sync isn’t enabled as it removes reddit functionally. Also, the reddit flair box should be checked before starting the bot

**Comment by Naturally-Delicious** [comment]
pfft so that was my problem. thanks, I always have ledy sync on since I have 2 3ds going at the same time. Will Reddit option be added for ledy sync imaboy321?

**Comment by k20stitch** [comment]
I believe it’s something the original author intends to do. Basically the reddit list needs to be done in the sync program, not the bots themselves. At least that’s how I would do it

**Comment by imaboy321** [comment]
It depends. You can't look at ledysync as a standard part of Ledybot. I never felt like touching the sync application but it really is a copy paste from the boy to the sync app. In reality, the reddit feature should be shared within both. You could have bots running on two different reddit threads (even though it is most unlikely). There are some things that should be shared between them that I may add when I get free time. I would be able to add more features if issues were created with update ideas.
