### ISSUE TITLE
Error with dropping a folder of .pk7 files into giveaway details

### ISSUE THREAD

**Issue by Naturally-Delicious** [olliz0r/Ledybot#25]
For a while now, whenever I drop a folder full of .pk7 into the giveaway details, ledybot would "skip" files, and not put them in the giveaway details. I would just drag the remaining pk7 files into the giveaway details window my self. Now today, I dropped in a folder this time, and only two came registered in the giveaway details. I had a lot of Pokemon to give out and didn't feel like dragging each file into the window. I saw that the 2 Pokemon that ledybot registered was a Muk and alola muk. And then it came to me, what if the alola pk.7 file is interfering with this? So I delete muk and alola muk from the folder and try dragging the folder into the giveaway details window again, and all the Pokemon got registered.

If you need clarification, please ask. I'm terrible when it comes to explaining things like this.

EDIT: Also suggestion, related to #20: Have an option for the bot to ignore anything in parenthesis ()  for the nickname requirement. For example, if you have `dave (1).pk7` Ledybot would ignore the `(1)` and just search for a Pokemon nicknamed `dave` in GTS. So if you have tons of Pokemon to give out, and you want the recipients to nickname their deposited mon to a specific nickname, it'll be easier to set up the files and such. Right now, you have to create each folder for a Pokemon, and there's no way to mass change file names across folders (at least that I know of...). So you'd have to go into each folder, nickname it to `dave`, exit and do it all over again. For small giveaways, this is like a piece of cake, but when you got over 30+ types of Pokemon to give out, it can get tedious and repetitive, and there are more prone to mistakes in file names and such.  Implementing this will allow you just to keep everything in one folder and be easier. I hope that makes sense 😓  Pls ask if you need clarification!

P.S Thank you for all that you do imaboy321 and @olliz0r ! This makes doing giveaways so much easier!! I will try to donate when I have the funds!

P.P.S Pls don't be pressured to implement this RIGHT away; it's just a small suggestion, get to it when you have free time!

PPPS: Ty for reading all this.

**Comment by imaboy321** [comment]
So since alolan and regular are the same dex number, the current release actually "breaks" when auto-adding duplicates. Since there are two different types, you can put the alolan in the "specific" folder so they can specifically request it and have the normal one as the default. The latest appveyor build actually fixes the issue which I found so it will skip duplicate species. https://ci.appveyor.com/project/imaboy321/ledybot/build/1.0.13/artifacts

**Comment by imaboy321** [comment]
I will also add the ignore parenthesis when I get the chance :)

**Comment by Naturally-Delicious** [comment]
That was what I thought. Thanks!
