### ISSUE TITLE
Anyway to tell if monster is trade legal?

### ISSUE THREAD

**Issue by k20stitch** [olliz0r/Ledybot#26]
Before I go writing a bunch of "endswith" conditions, do you guys have a way to check that a pokemon is GTS legal? i.e. It doesn't have any event ribbons, mega stones, z crystals, or cherish ball.

**Comment by Naturally-Delicious** [comment]
You could probably run a script in pkhex's batch editor that could check for the above. When it find the above, make the Pokémon shiny and you can go and make the changes. or if you're lazy like me, run the ga or what ever you're doing anyways and weed out the bad ones along the way.
