### ISSUE TITLE
Nicknames cut off

### ISSUE THREAD

**Issue by k20stitch** [olliz0r/Ledybot#28]
Gen 7 allows for 12 character nicknames, but ledybot snips off the last two characters. For example, user deposits "adamantflare", they don't get that pokemon and it shows up in the list as "adamantfla"

**Comment by Mitsukiii** [comment]
LedyBot doesn't snips any Charakters from Files, it inject the whole Bytes into the RAM.
[even the build in PKHeX allow 12 Charakters.
](https://github.com/olliz0r/Ledybot/blob/337fbb1fe5cf3170ea113b6e5d7274447e2d4271/Ledybot/PKHeX.cs#L355)

**Comment by k20stitch** [comment]
all I’m saying is that ledybot is parsing the first 10 characters of the Pokémon’s nickname. Not all 12. Go ahead and nickname a Pokémon 12 characters and trade it to yourself let me know what happens.

Nickname in ledy bot starts at address 0x14 of the block with a length of 20 and then \0 is trimmed from the front and back

**Comment by k20stitch** [comment]
I’m talking about the nickname of the incoming monster that’s used to check for variations of the one you’re giving away

**Comment by k20stitch** [comment]
Also, pretty sure the fix is to increase the count to 24 from 20 per the pk7 class in pkhex.

**Comment by k20stitch** [comment]
Issue fixed.
