### ISSUE TITLE
Find from start... to finish

### ISSUE THREAD

**Issue by k20stitch** [olliz0r/Ledybot#32]
Let's say at the end of the findfromstart state, I wanted to go to the next page instead of starting over (if not foundlastpage of course). I know there's other logic and what not needed, but i'm just interested in the bit that would increment one page.

**Comment by Mitsukiii** [comment]
[Thats what ure looking for.](https://github.com/olliz0r/Ledybot/blob/b9bc9654d6bd66b16ac12488f5609aa512065ae9/Ledybot/GTSBot7.cs#L395)

Its pretty easy, make a loop 
if (SEARCHDIRECTION_FROMFRONT && addr_PageStartingIndex == 0 && CurrentPage == 100) 
{}
//Press Right, Search again.


Depenting how many pages u want to search, for ex. if u want to search the first three pages, stop the loop after:
if (addr_PageStartingIndex == 200 && CurrentPage == 100)
{}

**Comment by k20stitch** [comment]
What does this too? 
waitTaskbool = Program.helper.waitNTRwrite(addr_PageStartingIndex, (uint)(startIndex + 200), iPID);

**Comment by Mitsukiii** [comment]
it writes the Page Number, ex. if you re on Page 1 the PageStartingIndex is 0, writing 200 to it will set u on Page 3, if u re on the latest entry on the current page and press right it will get u on Page 4.

**Comment by k20stitch** [comment]
Thanks. I was trying to see how search from the end works since that’s the bit that actually increments pages.

Looks like it jumps from page 1 to page 3 and checks if the third page exists to determine if the page 2 before it was the last page. 

Sounds like I don’t need to do any of that.

**Comment by k20stitch** [comment]
Is there a discord chat that you guys have?

**Comment by Mitsukiii** [comment]
Nope.


If u set the Page Number via Memory, u can hit Left/Right to -/+ The Page Number.
Or set the Page Nr. while pressing the Search Button.

**Comment by k20stitch** [comment]
Could you elaborate? I tried this

waitTaskbool = Program.helper.waitNTRwrite(addr_PageStartingIndex, (uint)(startIndex + 100), iPID);
If (waitTaskbool){
 StartIndex +=100
}

At first there is no left arrow (indicating on on the first page) but if I press right, then a left arrow appears.

If I press left twice I get taken to the end of a page but what page is this?

**Comment by Mitsukiii** [comment]
```(uint)(startIndex + 100)```

If you re on Page 1 its 0, u add +100 then it will be Page 2, u press Left Page 1 again.

**Comment by k20stitch** [comment]
Got it, makes sense now.

Check page 1
Set to page 3,
hit left to go to page 2,
Check page 2
hit right to go to page 3,
Check page 3
Set to page 5
hit left to go to page 4,
Check page 4, etc...
