### ISSUE TITLE
Desired result for "from the end"?

### ISSUE THREAD

**Issue by k20stitch** [olliz0r/Ledybot#35]
After initially searching from the last page, is the desired result to then just search the first page only? Just trying to confirm what i see in my logs.

**Comment by Mitsukiii** [comment]
Idk, what u mean exactly.

Bot tries to find the Last Page with
 If( Pagesize = 100)
{
//goto Nextpage
}
Else
{
//Last Page Found, searching this Page
}

**Comment by k20stitch** [comment]
My logs show 

Page 1 keep going
Page 2 keep going
Page 3 keep going
Page 4 keep going
Page 5 keep going
Page 6.... this is the last page, look for trade
Can’t find trade go to page 5
Can’t find trade go to page 4
Can’t find trade go to page 3
Can’t find trade go to page 2
Can’t find trade go to page 1
Can’t find trade go to page 1
Can’t find trade go to page 1
Can’t find trade go to page 1
Can’t find trade go to page 1
Can’t find trade go to page 1
Can’t find trade go to page 1

It makes sense since if you didn’t find anything on the last pages then you’re all caught up and you should only be looking at the first page but I’m just trying to clarify if this is by design or a bug/feature

The only way it ever goes back to the last page is if you stop and start the bot... or a trade is found.

**Comment by Mitsukiii** [comment]
thats how it works, new request will show on Page 1, if some1 deposit it while the bot searching it will be on Page 1.
