### ISSUE TITLE
Ledybot does not trade!

### ISSUE THREAD

**Issue by CosasDePuma** [olliz0r/Ledybot#37]
Cant get this to work.

It goes on the GTS and try to give the Pokemon to the selected player. It enter in the PC box to select the giveaway Pokemon but all Pokemon are in a gray color. It try to pick the first Pokemon in the box, indifferently what Pokemon it is. After trying to give the Pokemon and getting the error message because its a different Pokemon it goes back to the seek/deposit and does the same thing.

What is weird is that sometimes it adds entries to the table, showing a player info (FC and trade time included) of someone who you didn't trade and actually is asking for the Pokemon you are giving away.

I'm not sure if its supposed to do everything on the back without the player being able to see the trade or if I'm doing something wrong. I'm using NTR CFW 3.6 with InputRedirection.

**Comment by Mitsukiii** [comment]
Make sure ure on Box1 Slot 1 and dont trade illegal Pokemo.

**Comment by Naturally-Delicious** [comment]
U cannot trade illegal Pokémon and make sure ur on Box 1 slot 1.

**Comment by k20stitch** [comment]
This is an easy one.

Could be the following:

1. Pokemon is not GTS legal. I.e. it has event ribbons, cherish ball, z crystals, or mega stones attached to it.

2. Incorrect gender/level lock. You’re better off dragging the pk7 file into the giveaway details so it’s fills out the level and gender index for you.

**Comment by CosasDePuma** [comment]
Thank you for the reply, but I tried again and I got the same results.

I'm in Box 1 - Slot 1.
I'm trading newest PKHex Pokemons with Legality Flag in green.
I drag the pk7 file into the giveaway details window.

pk7 files used: https://file.io/qKvFp9

The game is Pokemon UltraSun in its newest patch.

Thanks again

**Comment by Mitsukiii** [comment]
remove all Ribbons.

**Comment by CosasDePuma** [comment]
Okay, all ribbons removed.

If I do the same process manually, I can do the trade.

Detailed problem:
- When Ledybot tries to trade, Box 1 Slot 1 PKM is in grey color (can't be traded)
- I stop the bot
- I try to trade the same PKM to the same person and the PKM is NOT in grey color (can be trade)

**Comment by Mitsukiii** [comment]
Ledybot dont have Logs. Does the ListView have the wanted Pokemon in?

**Comment by CosasDePuma** [comment]
The ListView show the trade attempts (even if they are unsuccessful)
The other ListView, in Giveaway Details, have the Pokemon I want to giveaway when autofilled options (dragged pk7 files). They are correct.

Maybe it's because Ledybot does not support USun/UMoon v1.2

**Comment by k20stitch** [comment]
Are you using a modded version of the bot? Or just the latest release?

Also, you say that it’s gray, but is the gray Pokémon the one that you’re actually trying to trade?

**Comment by k20stitch** [comment]
Also, please email me the pk7 file in question. antonio at newyorktuners dot com

**Comment by CosasDePuma** [comment]
@k20stitch:

> Are you using a modded version of the bot? Or just the latest release?

I'm using the latest release - commit d3e25df / version 2.5.1 named Small Fixes

> Also, you say that it’s gray, but is the gray Pokémon the one that you’re actually trying to trade?

![ledybottrade](https://user-images.githubusercontent.com/26680023/36706414-0a3baa32-1b6a-11e8-9431-5c2dc62d8a89.PNG)

Shiny Rattata to Giveaway is in Box 1 Slot 1 but it's in grey when Ledybot tries to trade it

![ledybot](https://user-images.githubusercontent.com/26680023/36706498-53a69222-1b6a-11e8-88ca-8705b85107c8.PNG)

Ledybot List View shows the unsuccessful trade

![manuallytrade](https://user-images.githubusercontent.com/26680023/36706443-28890c82-1b6a-11e8-9017-14ab3873a6e6.PNG)

Same Pokemon to same Trainer can be traded by me manually

![giveaway](https://user-images.githubusercontent.com/26680023/36706471-3f265940-1b6a-11e8-90b4-82f2bc53ac1f.PNG)

Giveaway Screen with dragged pk7 files

**Comment by CosasDePuma** [comment]
I noticed that Rattata is the number 19 in the NationalDex but the number 15 in the AlolaDex.
I tried to set Dex number to 15 in the Giveaway Details, but the bot does not recognize the trade haha

**Comment by CosasDePuma** [comment]
I was able to trade two pokemon! Ledybot only is able to trade the pk7 pokemon if it is been trading with a pokemon in the Page 1 Index 0 in the GTS. It's a bit disconcerting this problem...

Otherwise, the injected Pokemon is gray...

**Comment by k20stitch** [comment]
This is a known bug when adding two of the same Pokémon having one male and one female

**Comment by CosasDePuma** [comment]
That was an attempt.

Error persists if I only have one pokemon in Giveaway Details

**Comment by Naturally-Delicious** [comment]
You'll have to nickname the male/female pk7 "female"/"male" and then get
the people participating nickname heir Pokémon that so that ledybot knows
which to send.

**Comment by Mitsukiii** [comment]
oh i know the reason, u need to set your game language to english. Ledybot only works with English Language

**Comment by CosasDePuma** [comment]
Okay, finally we can close this issue. The problem was what @Mitsukiii said.

My game was in Spanish and the bot only works well in English language.
I just changed my game lang with PKHex.

Thank you to everyone! You are awesome!

Check my [Github](https://github.com/cosasdepuma) and [contact me](https://about.me/kikefontan) if you need some help in some project, I'm very grateful for everything!

**Comment by imaboy321** [comment]
Adding multi-language support has been thought of but the issue is with the offsets which change depending on the game language. Not all offsets do but the ones with the GTS do.
