### ISSUE TITLE
failure to connect

### ISSUE THREAD

**Issue by honcoop91** [olliz0r/Ledybot#45]
I am running input redirection and NTRboot3.6 and have the right IP, but Ledybot still freezes for a few seconds then says connection failed.. i am using it on a pocket wifi if that matters

**Comment by k20stitch** [comment]
Pocket WiFi? The 3ds and the computer need to be on the same network. If you’re talking about a mobile hotspot or jet pack it’s not going to work

**Comment by victorialatawiec1** [comment]
holy hell. i’m having the same problem. I’m running Luma3DS 9.0 and i literally have the latest versions of everything. i’m running NTRBoot, NTRs debugger, InputDirection, I’m online in-game, my DS’ IP address is correct, and I still can’t connect Ledybot to my 3DS. I’ve tried posting this question so many times and ive gotten absolutely no answer from anybody. can someone please help me figure this out?

**Comment by victorialatawiec1** [comment]
I also have Ultra Moon if that’s of any use....
