### ISSUE TITLE
UM crashing when I click "Connect".

### ISSUE THREAD

**Issue by Frumentarii** [olliz0r/Ledybot#47]
When I click connect on Ledybot, my game crashes and gives me an error, in Lebybot it still gives me the connection successful message. Using NTR Selector 3.6 on Ultra Moon, any workaround?

**Comment by k20stitch** [comment]
Did you start up the NTR input redirection?

**Comment by Mitsukiii** [comment]
its because the NFC Patch Offset, on Update 1.2 the Offset changed, if u can, compile the latest source its working there, SteveCookTU didnt pushed a release out.

**Comment by edwarbad23** [comment]
And How I compile the last source?

**Comment by k20stitch** [comment]
Download the entire project and click build in visual studio
