### ISSUE TITLE
Error when pressing "Start" on UM after compiling the latest source with the updated 1.2 NFC offsets

### ISSUE THREAD

**Issue by tehvik** [olliz0r/Ledybot#51]
Hello all. So I downloaded and built the latest source with the updated 1.2 offsets and I can finally connect on UM without crashing anymore. Sadly though, now I have another issue. 

When I press Start, so that the bot can start doing its thing on GTS, I get the following error http://prntscr.com/jtcrl7. Below I will list the whole details of the error so that can help someone identify the cause and hopefully help me fix it.  

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:3001
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Ledybot.GTSBot7..ctor(Int32 iP, Int32 iPtF, Int32 iPtFGender, Int32 iPtFLevel, Boolean bBlacklist, Boolean bReddit, Int32 iSearchDirection, String waittime, String consoleName, Boolean useLedySync, String ledySyncIp, String ledySyncPort, Int32 game, Boolean useLedybotTV, String ledybotTVIp, String ledybotTVPort) in C:\Users\maver\Desktop\LedyBot Pro Version\Ledybot-master\Ledybot\GTSBot7.cs:line 181
   at Ledybot.MainForm.<btn_Start_Click>d__33.MoveNext() in C:\Users\maver\Desktop\LedyBot Pro Version\Ledybot-master\Ledybot\Form1.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Ledybot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/maver/Desktop/LedyBot%20Pro%20Version/Ledybot-master/Ledybot/bin/Debug/Ledybot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

So to also give some more information on this, I built this version of ledybot from the latest source using visual studio express (no github extension). Dunno if this is the issue I just wanna give as much info as possible. Also I tested this version on both Moon and Ultra Moon, it connects fine on both, injects files fine, it just can't start doing its GTS trades.

Also the latest public release 2.5.1 works fine on Moon so it's not an Input Redirection issue I think.

This was all the info I could provide, feel free to ask me any more questions, thanks very much in advance for your time to look into this and really hope that someone could help me soon. I'm trying to fix this all day so I could giveaway some stuff. Again thanks a lot and hope someone could help me!

**Comment by Mitsukiii** [comment]
u need to connect to your 3ds ip address, not 127.0.0.1 // Localhost

**Comment by tehvik** [comment]
Of course I'm using my IP address and not the default one... As I already said in my post, I could connect just fine. I tried injecting and all the other features and they were working, it was only when pressing start that was giving this error. Anyway a friend already solved it for me. This change http://prntscr.com/jua991 fixed my issue and now it's working without problems.

**Comment by Mitsukiii** [comment]
kk fine.
