### ISSUE TITLE
Can not connect Ledybot to 3DS

### ISSUE THREAD

**Issue by victorialatawiec1** [olliz0r/Ledybot#54]
I am having a huge issue connecting Ledybot to my 3DS. I’m running Luma3DS 9.0 and i literally have the latest versions of everything. i’m running NTRBoot, NTRs debugger, InputDirection, I’m online in-game, my DS’ IP address is correct, and I still can’t connect Ledybot to my 3DS. I’ve tried posting this question so many times and ive gotten absolutely no answer from anybody. I also have ultra moon if that is of any use to anyone. I have no clue if I am doing something wrong or otherwise. Can somebody please help me figure out what I am doing wrong? Thank you :)

**Comment by SteveCookTU** [comment]
I am currently running through an update process. My latest push fixes this issue but I will not post a release download until I have gone through everything. Very sorry for the absence.
