### ISSUE TITLE
Not an issue just wanted to suggest a more updated guide for your readme

### ISSUE THREAD

**Issue by ItsDeidara** [olliz0r/Ledybot#6]
https://www.se7ensins.com/forums/threads/how-to-setup-a-pokemon-sun-and-moon-gts-giveaway-bot.1616037/

You don't have to use it of course. Figured id let you know about it since it may help with some confusion in regards to how to use this amazing tool

**Comment by imaboy321** [comment]
This is the old ledybot, please direct any tickets here: https://github.com/imaboy321/Ledybot
