### ISSUE TITLE
Compiling latest commit with an error

### ISSUE THREAD

**Issue by StarProgamGamer** [olliz0r/Ledybot#63]
I have tried compiling the latest commit and i get these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Form1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Ledybot			
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file BanlistDetails.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Ledybot			
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file GDInput.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Ledybot			
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file BLInput.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Ledybot			
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file GiveawayDetails.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Ledybot			
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0414	The field 'GTSBot7.val_BoxScreen' is assigned but its value is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\GTS7Bot.cs	65	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0414	The field 'GTSBot7.val_system' is assigned but its value is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\GTS7Bot.cs	66	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0414	The field 'GTSBot7.val_duringTrade' is assigned but its value is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\GTS7Bot.cs	67	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0414	The field 'GTSBot7.queueAttempts' is assigned but its value is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\GTS7Bot.cs	90	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0169	The field 'NTR.lastReadMemSeq' is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\NTRClient.cs	85	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0067	The event 'RemoteControl.onWriteLastLog' is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\RemoteControl.cs	40	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0067	The event 'RemoteControl.onWaitingForData' is never used	LedyLib	C:\Users\xxx\Desktop\Ledybot-master\LedyLib\RemoteControl.cs	41	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'Newtonsoft.Json' could not be found.	Ledybot			

Also, Visual Studio says there is supposed to be LedyDisc but its not there? I have never compiled a project before btw

**Comment by Bappsack** [comment]
Restore Nuget Packages?

**Comment by StarProgamGamer** [comment]
How do I do that?

**Comment by StarProgamGamer** [comment]
And i think i didn't download the latest version properly when i did as i got less errors when i did it through github

**Comment by Bappsack** [comment]
Right Click on the Main Ledybot Project(Project Explorer) - > Restore Nuget Packages.

**Comment by StarProgamGamer** [comment]
So i've actually managed to compile the latest commit now but it wont connect to my 2ds

**Comment by Bappsack** [comment]
is NTR + Input Redirection running? 
2DS? did u used the Mode3 Versions of both?

Minimize Game with Home. connect, open Game OR Connect before loading the save.

**Comment by StarProgamGamer** [comment]
i ran ntr mode 3 but luma 9.1 has built in input redirection so i use that

**Comment by StarProgamGamer** [comment]
is 3.6 the one i should be using for ntr?

**Comment by Bappsack** [comment]
yes, luma IR doesnt work with NTR

**Comment by StarProgamGamer** [comment]
oh so where can i get the mode 3 input redirection? Where i downloaded there was only one version

**Comment by Bappsack** [comment]
https://github.com/Stary2001/InputRedirection/releases

**Comment by StarProgamGamer** [comment]
I got the whole thing working thanks for helping

**Comment by StarProgamGamer** [comment]
Well I haven't tested it out properly but it connected to my 2ds

**Comment by Bappsack** [comment]
@SteveCookTU , u know what todo m8.
