### ISSUE TITLE
Randomly searches for Abra then highlights quit

### ISSUE THREAD

**Issue by sonicbrawler** [olliz0r/Ledybot#7]
I used this for about 5 or so hours last night. Ran into some issues (where it would end up searching for an abra even if i dont say to, then it would end up highlighting quit and break) not sure if its due to my crappy college wifi and some interference, but it happened a lot

**Comment by imaboy321** [comment]
This is a connection/timing issue within the program. If a connection delays it could mess up the timers and it will happen once in awhile. I plan on eventually adding a calibration based off connection speeds.

**Comment by imaboy321** [comment]
This is the old ledybot, please direct any tickets here: https://github.com/imaboy321/Ledybot
